public class myfirstclass {
    Public Void area (integer l , integer h)
    {
        decimal a;
           a= l*h;
        system.debug(a); 
    }
public  decimal area1 (integer l, integer h )
{
    decimal a ;
    a=l*h;
    return a;
        
}
     public void area2()  
         
     {
         decimal a;
         integer l;
             integer h;
          
      l=4;
      h=8;
          a=l*h;
         system.debug('this is non parameterize'+a);
         
     }


public decimal area3()
{
   decimal a;
    integer l=34;
    integer h=9;
    a=l*h;
    return a;
        
    
}}